/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAvatar: typeof import('primevue/avatar')['default']
    PrimeBadge: typeof import('primevue/badge')['default']
    PrimeBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDropdown: typeof import('primevue/dropdown')['default']
    PrimeFileUpload: typeof import('primevue/fileupload')['default']
    PrimeForm: typeof import('@primevue/forms/form')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeOverlayBadge: typeof import('primevue/overlaybadge')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimeRating: typeof import('primevue/rating')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
